// Contractor PO list page. Read-only view onto the POs generated by
// reconcileContractorPO server-side. Click a row to drill into the
// linked work items (their qaStatus and contractorPayableAmount drive
// the open/closed status of the parent PO).

import React, { useEffect, useMemo, useState } from 'react';
import { Search, CheckCircle2, Circle, ExternalLink, Briefcase } from 'lucide-react';
import { apiRequest } from '../../lib/apiClient';
import { useAuth } from '../../contexts/AuthContext';
import { useProjectStore } from '../../store/pm/useProjectStore';

interface ContractorPOWorkItem {
  id: string;
  title: string;
  qaStatus: string | null;
  contractorPayableAmount: number | string | null;
  status: string | null;
}

interface ContractorPO {
  id: string;
  displayCode: string;
  projectId: string;
  contractorId: string;
  status: 'open' | 'closed' | string;
  totalAmount: number | string;
  itemCount: number;
  approvedCount: number;
  openedAt: string;
  closedAt: string | null;
  project?: { id: string; name: string };
  contractor?: { id: string; name: string; email: string | null };
  workItems?: ContractorPOWorkItem[];
}

function fmtAmount(value: number | string | null | undefined): string {
  if (value === null || value === undefined) return '-';
  const n = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(n)) return '-';
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
}

const ContractorPurchaseOrdersPage: React.FC = () => {
  const { user } = useAuth();
  const { activeProjectId } = useProjectStore();
  const [pos, setPOs] = useState<ContractorPO[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'open' | 'closed'>('all');
  const [search, setSearch] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);

  useEffect(() => {
    if (!user?.id) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    const qs = new URLSearchParams({ userId: user.id, take: '200' });
    if (activeProjectId) qs.set('projectId', activeProjectId);
    apiRequest<{ purchaseOrders: ContractorPO[] }>(`/api/v1/pm/contractor-pos?${qs.toString()}`)
      .then((res) => { if (!cancelled) setPOs(res.purchaseOrders || []); })
      .catch((err) => { if (!cancelled) setError(err?.message || 'Failed to load purchase orders.'); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [user?.id, activeProjectId]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    return pos.filter((po) => {
      if (filter !== 'all' && po.status !== filter) return false;
      if (!q) return true;
      return (
        po.displayCode.toLowerCase().includes(q)
        || (po.contractor?.name || '').toLowerCase().includes(q)
        || (po.project?.name || '').toLowerCase().includes(q)
      );
    });
  }, [pos, filter, search]);

  const selected = useMemo(
    () => filtered.find((p) => p.id === selectedId) || null,
    [filtered, selectedId],
  );

  return (
    <div className="p-6 space-y-4">
      <div className="flex items-center gap-3 flex-wrap">
        <Briefcase size={18} className="text-emerald-400" />
        <h1 className="text-lg font-semibold text-primary">Contractor Purchase Orders</h1>
        <span className="text-xs text-muted">
          Auto-generated when a telecom task with a contractor gets a non-null payable. Closes when every linked task is QA-approved.
        </span>
      </div>

      <div className="flex items-center gap-2 flex-wrap">
        <div className="relative">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted pointer-events-none" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by PO code, contractor, project…"
            className="w-80 pl-9 pr-3 py-2 text-xs bg-surface border border-input rounded-lg text-primary"
          />
        </div>
        {(['all', 'open', 'closed'] as const).map((f) => (
          <button
            key={f}
            type="button"
            onClick={() => setFilter(f)}
            className={`px-3 py-1.5 rounded-lg text-xs ${
              filter === f ? 'bg-blue-600 text-white' : 'bg-surface border border-input text-secondary'
            }`}
          >
            {f === 'all' ? 'All' : f === 'open' ? 'Open' : 'Closed'}
          </button>
        ))}
        <span className="text-[11px] text-muted ml-auto">
          {filtered.length} of {pos.length} purchase orders
        </span>
      </div>

      {error && <p className="text-xs text-rose-400">{error}</p>}
      {loading && <p className="text-xs text-muted">Loading…</p>}

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_420px] gap-4">
        <div className="rounded-xl border border-border/70 overflow-hidden">
          <table className="w-full text-xs">
            <thead className="bg-surface text-muted">
              <tr>
                <th className="text-left px-4 py-2.5">PO</th>
                <th className="text-left px-4 py-2.5">Contractor</th>
                <th className="text-left px-4 py-2.5">Project</th>
                <th className="text-right px-4 py-2.5">Total</th>
                <th className="text-center px-4 py-2.5">Items</th>
                <th className="text-center px-4 py-2.5">Status</th>
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 && !loading && (
                <tr><td colSpan={6} className="text-center py-10 text-muted">No purchase orders yet.</td></tr>
              )}
              {filtered.map((po) => {
                const isOpen = po.status === 'open';
                return (
                  <tr
                    key={po.id}
                    onClick={() => setSelectedId(po.id)}
                    className={`border-t border-border/40 cursor-pointer hover:bg-surface/50 ${selectedId === po.id ? 'bg-surface' : ''}`}
                  >
                    <td className="px-4 py-2.5 font-mono text-primary">{po.displayCode}</td>
                    <td className="px-4 py-2.5 text-primary">{po.contractor?.name || '—'}</td>
                    <td className="px-4 py-2.5 text-secondary">{po.project?.name || po.projectId}</td>
                    <td className="px-4 py-2.5 text-right font-mono text-primary">{fmtAmount(po.totalAmount)}</td>
                    <td className="px-4 py-2.5 text-center text-secondary">{po.approvedCount}/{po.itemCount}</td>
                    <td className="px-4 py-2.5 text-center">
                      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold ${
                        isOpen ? 'bg-amber-500/10 text-amber-300 border border-amber-500/30'
                               : 'bg-emerald-500/10 text-emerald-300 border border-emerald-500/30'
                      }`}>
                        {isOpen ? <Circle size={10} /> : <CheckCircle2 size={10} />}
                        {isOpen ? 'Open' : 'Closed'}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {selected && (
          <aside className="rounded-xl border border-border/70 bg-card p-4 space-y-3 h-fit sticky top-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-[11px] uppercase tracking-wider text-muted">Purchase Order</p>
                <p className="text-base font-mono text-primary">{selected.displayCode}</p>
              </div>
              <button
                type="button"
                onClick={() => setSelectedId(null)}
                className="text-xs text-muted hover:text-primary"
              >
                Close
              </button>
            </div>
            <div className="grid grid-cols-2 gap-3 text-xs">
              <div>
                <p className="text-muted">Contractor</p>
                <p className="text-primary">{selected.contractor?.name || '—'}</p>
                {selected.contractor?.email && (
                  <p className="text-muted text-[10px]">{selected.contractor.email}</p>
                )}
              </div>
              <div>
                <p className="text-muted">Project</p>
                <p className="text-primary">{selected.project?.name || selected.projectId}</p>
              </div>
              <div>
                <p className="text-muted">Total</p>
                <p className="text-primary font-mono">{fmtAmount(selected.totalAmount)}</p>
              </div>
              <div>
                <p className="text-muted">Progress</p>
                <p className="text-primary">{selected.approvedCount}/{selected.itemCount} approved</p>
              </div>
              <div>
                <p className="text-muted">Opened</p>
                <p className="text-primary">{new Date(selected.openedAt).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-muted">Closed</p>
                <p className="text-primary">{selected.closedAt ? new Date(selected.closedAt).toLocaleDateString() : '—'}</p>
              </div>
            </div>
            <div>
              <p className="text-[11px] uppercase tracking-wider text-muted mb-1.5">Linked work items</p>
              <div className="space-y-1.5 max-h-96 overflow-y-auto">
                {(selected.workItems || []).map((wi) => {
                  const approved = (wi.qaStatus || '').toLowerCase() === 'approved';
                  return (
                    <div key={wi.id} className="flex items-center justify-between gap-2 rounded-lg border border-border/60 bg-surface px-3 py-2">
                      <div className="min-w-0">
                        <p className="text-xs text-primary truncate">{wi.title}</p>
                        <p className="text-[10px] text-muted">
                          QA {wi.qaStatus || 'pending'} · {fmtAmount(wi.contractorPayableAmount)}
                        </p>
                      </div>
                      {approved
                        ? <CheckCircle2 size={14} className="text-emerald-400 shrink-0" />
                        : <Circle size={14} className="text-amber-400 shrink-0" />}
                    </div>
                  );
                })}
                {(selected.workItems || []).length === 0 && (
                  <p className="text-xs text-muted">No items linked.</p>
                )}
              </div>
            </div>
          </aside>
        )}
      </div>
    </div>
  );
};

export default ContractorPurchaseOrdersPage;
