-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "costHT" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "costTTC" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN     "vatAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vatRate" DECIMAL(7,4) NOT NULL DEFAULT 16;
